name: tech_world
description: "A world of tech adventures."
publish_to: "none"
version: 0.0.0+1

environment:
  sdk: ^3.0.0

dependencies:
  flutter:
    sdk: flutter
  livekit_client: ^2.5.1
  flutter_webrtc: ^1.2.0  # Required for controls.dart
  shared_preferences: ^2.2.3 # currently used by livekit code
  flame: ^1.18.0
  a_star_algorithm: ^0.3.2
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  cloud_functions: ^6.0.2
  tech_world_networking_types:
    # path: ../../dart/interfaces/tech_world_networking_types
    git: https://github.com/enspyrco/tech_world_networking_types
  web_socket_channel: ^3.0.0 # used by networking service
  collection: ^1.19.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter

  flutter_lints: ^4.0.0
  stream_channel: ^2.1.2 # for mocking the web_socket_channel connected to the server

flutter:
  uses-material-design: true
  assets:
    - assets/images/
