name: tech_world
description: "A world of tech adventures."
publish_to: "none"
version: 0.0.0+1

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  livekit_client: ^2.5.1
  flutter_webrtc: ^1.2.0 # Required for controls.dart
  shared_preferences: ^2.2.3 # currently used by livekit code
  flame: ^1.18.0
  pathfinding: ^3.0.1
  firebase_core: ^4.1.1
  cloud_firestore: ^6.0.2
  firebase_auth: ^6.1.0
  sign_in_with_apple: ^7.0.1
  crypto: ^3.0.6
  google_sign_in: ^7.2.0
  cloud_functions: ^6.0.2
  collection: ^1.19.1
  ffi: ^2.1.5
  web: ^1.1.0 # For web video capture APIs

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flame_test: ^1.15.0

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4
  fake_cloud_firestore: ^4.0.1
  flutter_native_splash: ^2.4.7

flutter_launcher_icons:
  image_path: "assets/icon/app_icon.png"
  android: true
  ios: true
  macos:
    generate: true
    image_path: "assets/icon/app_icon.png"
  web:
    generate: true
    image_path: "assets/icon/app_icon.png"
    background_color: "#000000"
    theme_color: "#000000"

flutter:
  uses-material-design: true
  assets:
    - assets/images/
  shaders:
    - shaders/video_bubble.frag
